In [1]:
import numpy as np
from sklearn.utils import shuffle

X0 = np.random.randn(100, 2) - 1
X1 = np.random.randn(100, 2) + 1
X = np.vstack([X0, X1])
t = np.vstack([np.zeros([100, 1]), np.ones([100, 1])])

In [10]:
X, t = shuffle(X, t)

X_train, X_test = X[:150], X[150:]
t_train, t_test = t[:150], t[150:]

In [13]:
# Initialize weight
W = np.random.randn(2, 1) * 0.01

def sigm(x):
    return 1/(1+np.exp(-x))

def NLL(y, t):
    return -np.mean(t*np.log(y) + (1-t)*np.log(1-y))

In [14]:
# Forward
z = X_train @ W
y = sigm(z)
loss = NLL(y, t_train)

# Loss
print(f'Loss: {loss:.3f}')

Loss: 0.692


In [16]:
m = y.shape[0]
dy = (y-t_train)/(m * (y - y*y))
dz = sigm(z)*(1-sigm(z))
dW = X_train.T @ (dz * dy)

In [21]:
alpha = 0.1
W = W - alpha * dW

In [23]:
grad_loglik_z = (t_train-y)/(y - y*y) * dz
grad_loglik_W = grad_loglik_z * X_train

In [27]:
F = np.cov(grad_loglik_W.T)
F

array([[0.25286861, 0.00473385],
       [0.00473385, 0.20251003]])

In [28]:
W = W - alpha * np.linalg.inv(F) @ dW
W

array([[0.23597271],
       [0.30477862]])

In [29]:
# Training
for it in range(5):
    # Forward
    z = X_train @ W
    y = sigm(z)
    loss = NLL(y, t_train)

    # Loss
    print(f'Loss: {loss:.3f}')

    m = y.shape[0]

    dy = (y-t_train)/(m * (y - y*y))
    dz = sigm(z)*(1-sigm(z))
    dW = X_train.T @ (dz * dy)

    grad_loglik_z = (t_train-y)/(y - y*y) * dz
    grad_loglik_W = grad_loglik_z * X_train
    F = np.cov(grad_loglik_W.T)

    # Step
    W = W - alpha * np.linalg.inv(F) @ dW
    # W = W - alpha * dW

print(W)

Loss: 0.473
Loss: 0.270
Loss: 0.174
Loss: 0.163
Loss: 0.158
[[1.90740969]
 [2.27859758]]


In [30]:
y = sigm(X_test @ W).ravel()
acc = np.mean((y >= 0.5) == t_test.ravel())

print(f'Accuracy: {acc:.3f}')

Accuracy: 0.980
